### PR TITLE
[type refactor] add nacos sync starter pom placeholder.

### PR DESCRIPTION
**Pull request by qicz**
append the `shenyu-spring-boot-starter-sync-data-nacos` placeholder to `bootstrap` pom.

### CODE REVIEW

**Comment by yu199195** [comment]
we cannot  add nacos

**Comment by qicz** [comment]
> we cannot add nacos

I see, just placeholder like `zookeeper sync starter`

**Comment by yu199195** [comment]
sync data to nacos is a way, but is not provided by default~   shenyu-boostrap its release package in apache,  so can not add nacos

**Comment by qicz** [comment]
> sync data to nacos is a way, but is not provided by default~ shenyu-boostrap its release package in apache, so can not add nacos

ok

**Pull request closed without merging**
