### PR TITLE
[ISSUE #1867] Dynamic generate static files.

### LINKED ISSUE #1867: Replace static files in shenyu-admin with maven plugin to dynamic generate
#### Is your feature request related to a problem? Please describe

I think it is not reasonable that place the follow files to `shenyu-admin/src/main/resources/static`
```
favicon.ico
index.{xxx}.css
index.{xxx}.js
index.html
```

It should  dynamic generate by maven plugin.

#### Describe the solution you'd like

I will use `com.github.eirslett:frontend-maven-plugin` to execute `npm install` and `npm run build`.
After build statis files, I will use `maven-resources-plugin` to move files in `dist` to `shenyu-admin`.

#### Additional context

reference: [skywalking apm-webapp pom.xml](https://github.com/apache/skywalking/blob/master/apm-webapp/pom.xml)

### PR DESCRIPTION
**Pull request by Switch-vov**
Dynamic generate static files; eg. Fixes #1867

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by Switch-vov** [comment]
@dengliming  I had revert that logic. #1867

**Comment by Switch-vov** [comment]
check error https://github.com/apache/incubator-shenyu/pull/1873/checks?check_run_id=3248390260#step:7:4059 .
```bash
2021-08-05 03:56:43 [main] INFO  org.apache.shenyu.admin.service.impl.UpstreamCheckService - upstream host null is exists.
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.594 s <<< FAILURE! - in org.apache.shenyu.admin.service.UpstreamCheckServiceTest
Error:  org.apache.shenyu.admin.service.UpstreamCheckServiceTest.testScheduled  Time elapsed: 0.196 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <2>
     but: was <3>
	at org.apache.shenyu.admin.service.UpstreamCheckServiceTest.testScheduled(UpstreamCheckServiceTest.java:144)
```

but in my local environment:

```bash
$ pwd
/Users/switch/IdeaProjects/incubator-shenyu/shenyu-admin
$ ../mvnw -B clean install
...
[INFO] Installing /Users/switch/IdeaProjects/incubator-shenyu/shenyu-admin/target/shenyu-admin-sources.jar to /Users/switch/.m2/repository/org/apache/shenyu/shenyu-admin/2.4.0-SNAPSHOT/shenyu-admin-2.4.0-SNAPSHOT-sources.jar
[INFO] Installing /Users/switch/IdeaProjects/incubator-shenyu/shenyu-admin/target/shenyu-admin-javadoc.jar to /Users/switch/.m2/repository/org/apache/shenyu/shenyu-admin/2.4.0-SNAPSHOT/shenyu-admin-2.4.0-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:22 min
[INFO] Finished at: 2021-08-05T12:10:40+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by Switch-vov** [comment]
Why `HealthCheckTaskTest.testRun:91` is failure?

```bash
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shenyu.common.exception.ShenyuExceptionTest
[INFO] Running org.apache.shenyu.common.healthcheck.HealthCheckTaskTest
09:45:07.789 [shenyu-upstream-health-check-request-4] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] upstream  health check failed, server is offline.
09:45:07.836 [shenyu-upstream-health-check-3] ERROR org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Meet problem: 
java.util.ConcurrentModificationException: null
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at org.apache.shenyu.common.healthcheck.HealthCheckTask.lambda$check$3(HealthCheckTask.java:144)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.apache.shenyu.common.healthcheck.HealthCheckTask.check(HealthCheckTask.java:144)
	at org.apache.shenyu.common.healthcheck.HealthCheckTask.doHealthCheck(HealthCheckTask.java:139)
	at org.apache.shenyu.common.healthcheck.HealthCheckTask.healthCheck(HealthCheckTask.java:127)
	at org.apache.shenyu.common.healthcheck.HealthCheckTask.run(HealthCheckTask.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:45:08.611 [shenyu-upstream-health-check-request-4] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] upstream http://www.baidu.com health check passed, server is back online.
09:45:09.654 [main] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] all upstream as removed.
09:45:09.656 [main] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] all upstream as removed.
09:45:09.658 [main] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] upstream null was removed.
09:45:09.661 [main] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] upstream null was removed.
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.23 s <<< FAILURE! - in org.apache.shenyu.common.healthcheck.HealthCheckTaskTest
Error:  org.apache.shenyu.common.healthcheck.HealthCheckTaskTest.testRun  Time elapsed: 6.193 s  <<< FAILURE!
java.lang.AssertionError
	at org.apache.shenyu.common.healthcheck.HealthCheckTaskTest.testRun(HealthCheckTaskTest.java:91)

[INFO] Running org.apache.shenyu.common.utils.CollectionUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.CollectionUtilsTest
[INFO] Running org.apache.shenyu.common.utils.DateUtilsTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.142 s - in org.apache.shenyu.common.utils.DateUtilsTest
[INFO] Running org.apache.shenyu.common.utils.GsonUtilsTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.apache.shenyu.common.utils.GsonUtilsTest
[INFO] Running org.apache.shenyu.common.utils.HttpParamConverterTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.HttpParamConverterTest
[INFO] Running org.apache.shenyu.common.utils.IpUtilsTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 s - in org.apache.shenyu.common.utils.IpUtilsTest
[INFO] Running org.apache.shenyu.common.utils.JsonUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.53 s - in org.apache.shenyu.common.utils.JsonUtilsTest
[INFO] Running org.apache.shenyu.common.utils.LogUtilsTest
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.592 s - in org.apache.shenyu.common.utils.LogUtilsTest
[INFO] Running org.apache.shenyu.common.utils.Md5UtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.Md5UtilsTest
[INFO] Running org.apache.shenyu.common.utils.ParamCheckUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.ParamCheckUtilsTest
[INFO] Running org.apache.shenyu.common.utils.PathMatchUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.PathMatchUtilsTest
[INFO] Running org.apache.shenyu.common.utils.ReflectUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.shenyu.common.utils.ReflectUtilsTest
[INFO] Running org.apache.shenyu.common.utils.SignUtilsTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.SignUtilsTest
[INFO] Running org.apache.shenyu.common.utils.SpiLoadFactoryTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.apache.shenyu.common.utils.SpiLoadFactoryTest
[INFO] Running org.apache.shenyu.common.utils.ThreadUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 s - in org.apache.shenyu.common.utils.ThreadUtilsTest
[INFO] Running org.apache.shenyu.common.utils.UpstreamCheckUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.062 s - in org.apache.shenyu.common.utils.UpstreamCheckUtilsTest
[INFO] Running org.apache.shenyu.common.utils.UUIDUtilsTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.apache.shenyu.common.utils.UUIDUtilsTest
[INFO] Running org.apache.shenyu.common.utils.VersionUtilsTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.shenyu.common.utils.VersionUtilsTest
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    HealthCheckTaskTest.testRun:91
[INFO] 
Error:  Tests run: 135, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for shenyu 2.4.0-SNAPSHOT:
[INFO] 
[INFO] shenyu ............................................. SUCCESS [  6.462 s]
[INFO] shenyu-common ...................................... FAILURE [ 21.227 s]
[INFO] shenyu-disruptor ................................... SKIPPED
[INFO] shenyu-spi ......................................... SKIPPED
```

**Comment by midnight2104** [comment]
hi, please modify your title name by [Apache ShenYu Issue And Pull Request](https://shenyu.apache.org/community/issue-pr/) . your pr name like this:  [ISSUE #1867] dynamic generate static files .

**Comment by Switch-vov** [comment]
> hi, please modify your title name by [Apache ShenYu Issue And Pull Request](https://shenyu.apache.org/community/issue-pr/) . your pr name like this: [ISSUE #1867] dynamic generate static files .

done

**Comment by midnight2104** [comment]
hello @Switch-vov , you may be need to resolve conflict and resubmit

**Comment by Switch-vov** [comment]
> hello @Switch-vov , you may be need to resolve conflict and resubmit

done.

**Comment by Switch-vov** [comment]
@dengliming please review it. :)

**Pull request closed without merging**
