### PR TITLE
[ISSUE #1861] fix duplicated http header

### PR DESCRIPTION
**Pull request by dragon-zhang**
fix https://github.com/apache/incubator-shenyu/issues/1861

also fix another problem, desc here: In `org.apache.shenyu.web.filter.CrossFilter`, we had add some `http header`, when `clientResponse` has the same `http header`, duplicated `http header` will be returned

### CODE REVIEW

**Comment by dragon-zhang** [comment]
Please review `file changed` directly

**Review by tydhot — COMMENTED** [review]
maybe add a test case about it is better

**Comment by dragon-zhang** [comment]
> maybe add a test case about it is better

Got it, test case will be added as soon as possible

**Comment by dragon-zhang** [comment]
I found everything goes well, the old version of `org.dromara.soul.web.filter.CrossFilter` simply add the http header.
```java
public class CrossFilter implements WebFilter {
    //......
    @Override
    @SuppressWarnings("all")
    public Mono<Void> filter(final ServerWebExchange exchange, final WebFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        if (CorsUtils.isCorsRequest(request)) {
            ServerHttpResponse response = exchange.getResponse();
            HttpHeaders headers = response.getHeaders();
            headers.add("Access-Control-Allow-Origin", ALLOWED_ORIGIN);
            headers.add("Access-Control-Allow-Methods", ALLOWED_METHODS);
            headers.add("Access-Control-Max-Age", MAX_AGE);
            headers.add("Access-Control-Allow-Headers", ALLOWED_HEADERS);
            headers.add("Access-Control-Expose-Headers", ALLOWED_EXPOSE);
            headers.add("Access-Control-Allow-Credentials", "true");
            if (request.getMethod() == HttpMethod.OPTIONS) {
                response.setStatusCode(HttpStatus.OK);
                return Mono.empty();
            }
        }
        return chain.filter(exchange);
    }
}
```
And in `org.apache.shenyu.web.filter.CrossFilter`, it has been processed for the same request header by `filterSameHeader`.
```java
    /**
     * Filter the same headers.
     *
     * @param headers the response headers
     * @param header header name
     * @param newHeaderValue the new value for header
     */
    private void filterSameHeader(final HttpHeaders headers, final String header, final String newHeaderValue) {
        if (StringUtils.isBlank(newHeaderValue)) {
            return;
        }
        if (ALL.equals(newHeaderValue.trim())) {
            headers.set(header, ALL);
            return;
        }
        final Set<String> newHeaders = Stream.of(newHeaderValue.split(","))
                .map(String::trim).collect(Collectors.toSet());
        List<String> originHeaders = headers.get(header);
        if (CollectionUtils.isNotEmpty(originHeaders)) {
            if (originHeaders.contains(ALL)) {
                return;
            }
            originHeaders = Stream.of(String.join(",", originHeaders).split(","))
                    .map(String::trim).collect(Collectors.toList());
            newHeaders.addAll(originHeaders);
        }
        headers.set(header, String.join(",", newHeaders));
    }
```

**Comment by dragon-zhang** [comment]
This PR is out of date, so I will close this PR

**Comment by yu199195** [comment]
Hi, 

> This PR is out of date, so I will close this PR

out of date is mean?

**Comment by dragon-zhang** [comment]
> Hi,
> 
> > This PR is out of date, so I will close this PR
> 
> out of date is mean?

The problem has been solved in the lateast version.

**Pull request closed without merging**
