### PR TITLE
[ISSUE #1918] fix client : retry the connection add log and increase sleep time

### PR DESCRIPTION
**Pull request by zhaoguhong**
fix client : retry the connection add log and increase sleep time #1918

### CODE REVIEW

**Comment by tydhot** [comment]
welcome! thanks

**Comment by tydhot** [comment]
@yu199195 @zhaoguhong I think we should make it termination after a large loop. It is a waste of thread.

**Comment by zhaoguhong** [comment]
> @yu199195 @zhaoguhong I think we should make it termination after a large loop. It is a waste of thread.

I agree. It can be terminated after three minutes

**Review by SaberSola — APPROVED** [review]

**Comment by SaberSola** [comment]
Hi,Do you have plan to add a time limit like three minutes on this PR

**Review by yu199195 — APPROVED** [review]

**Comment by zhaoguhong** [comment]
> Hi,Do you have plan to add a time limit like three minutes on this PR

Yes,But I still have a question, if the connection fails after three minutes，Should terminate or ignore the error and continue to register?

**Pull request merged**
