### PR TITLE
[type: feature] support rpc unwrap result

### PR DESCRIPTION
**Pull request by dragon-zhang**
now rpc response:
{
    "code":200,
    "message":"OK",
    "data":{
        "id":3,
        "name":"hello world shenyu Alibaba Dubbo, findById"
    }
}

when config rpc annotation like this:
@ShenyuDubboClient(path = "/findById", desc = "Query by Id", wrap = false)

you will get rpc response:
{
    "id":3,
    "name":"hello world shenyu Alibaba Dubbo, findById"
}

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by heihei180** [comment]
I wonder why？ @dragon-zhang

**Review by cysy-lli — APPROVED** [review]
good

**Comment by KevinClair** [comment]
see here [CustomReuslt](https://shenyu.apache.org/zh/docs/developer/custom-result)

**Comment by dragon-zhang** [comment]
> see here [CustomReuslt](https://shenyu.apache.org/zh/docs/developer/custom-result)

Thank you for your answer, but don't you think this implmentation is a little heavy?

**Comment by KevinClair** [comment]
First of all, in my opinion,wrap result is a correct behavior, you can set some code and message to show your api's status.
Secondly, shenyu has been provided a way to extend and it can slove your problem,no need to add a new way.

**Comment by dragon-zhang** [comment]
How to achieve the coexistence of wrap and unwrap ?

------------------ Original ------------------
From: Kevin Clair ***@***.***&gt;
Date: Fri,Sep 3,2021 0:31 AM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [type: feature] support rpc unwrap result (#2011)





 
First of all, in my opinion,wrap result is a correct behavior, you can set some code and message to show your api's status.
 Secondly, shenyu has been provided a way to extend and it can slove your problem,no need to add a new way.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KevinClair** [comment]
That's weird.

**Comment by yu199195** [comment]
sql can add warp filed?

**Comment by dragon-zhang** [comment]
> sql can add warp filed?

rpc client annotation can add warp filed, just like this below:
@ShenyuDubboClient(path = "/findById", desc = "Query by Id", wrap = false)

supported other rpc client annotation, also.

**Comment by yu199195** [comment]
@dragon-zhang 

I think Your idea is good to add a field, does the sql statement need to add it?

**Comment by dragon-zhang** [comment]
> @dragon-zhang
> 
> I think Your idea is good to add a field, does the sql statement need to add it?

nop

**Comment by dragon-zhang** [comment]
@yu199195 When are you going to merge my code?

**Comment by qicz** [comment]
#2530 supports the RPC response result unwrap. so I will close this pr.

**Comment by dragon-zhang** [comment]
got it

**Pull request closed without merging**
