### PR TITLE
refactor: move admin-config to resource directory and extract common …

### PR DESCRIPTION
**Pull request by CarolineZhang666**
refactor: move admin-config to resource directory and extract common dependencies to pom.xml

// Describe your PR here; eg. Fixes #issueNo

Make sure that:

- [x ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [x ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by CarolineZhang666** [comment]
@flycash, please help to review this PR

**Comment by dengliming** [comment]
?

**Comment by CarolineZhang666** [comment]
> ?

what is mean ?

**Comment by CarolineZhang666** [comment]
> ?

>??

**Review by dengliming — APPROVED** [review]

**Pull request merged**
