### PR TITLE
[ISSUE #1866] Delete @Getter from <shenyu-bootstrap>.

### PR DESCRIPTION
**Pull request by javaChain**
// Describe your PR here; eg. Fixes #issueNo

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by javaChain** [comment]
@dengliming can you help me plz.

**Comment by dengliming** [comment]
> @dengliming can you help me plz.

What can I do for you? @javaChain

**Comment by spance** [comment]
Why remove the `@getter` (lombok annotation)?

**Comment by javaChain** [comment]
> Why remove the `@getter` (lombok annotation)?

yeah `@getter` is lombok annotation.

**Comment by javaChain** [comment]
@dengliming can you help me `Review required`?

**Review by HessTina-YuI — APPROVED** [review]

**Pull request merged**
