### PR TITLE
[fix admin #3090 ] Fix click on the "EditResourceDetails" button error

### PR DESCRIPTION
**Pull request by wklong**
[fix admin #3090 ] Fix Click on the EditResourceDetails button error

### CODE REVIEW

**Comment by li-keguo** [comment]
you must fix unit test

**Comment by wklong** [comment]
> you must fix unit test
Yes, I'll fix it according to the report tomorrow

**Comment by wklong** [comment]
> you must fix unit test
Yes, I'll fix it according to the report tomorrow

**Comment by wklong** [comment]
> you must fix unit test

done

**Review by yu199195 — DISMISSED** [review]

**Review by yu199195 — APPROVED** [review]

**Pull request merged**
