### PR TITLE
[ISSUE #3511 ]upgrade tool packages, for example: common-collectiions, gson, common…

### LINKED ISSUE #3511: [Task] upgrade shenyu dependency task1
### Description

upgrade shenyu dependency and make sure dependency version test case.

### Task List

1. 1.  [x] upgrade shenyu resilience4j plugin dependency and test. @moremind 
2. 2.  [x] upgrade shenyu hystrix plugin dependency and test. @moremind 
3. 3.  [x] upgrade shenyu jwt plugin dependency and test. @moremind 
4. 4.  [x] upgrade shenyu logging-rocketmq plugin dependency and test. @moremind 
5. 5.  [x] upgrade shenyu motan plugin dependency and test. @renzhuyan 
6. 6.  [x] upgrade mybatis , druid, pagehelper version and test. @renzhuyan 
7. 7.  [x] upgrade tool packages, for example: common-collectiions, gson, common-lang and xstream and so so, @renzhuyan

### PR DESCRIPTION
**Pull request by renzhuyan**
…-lang and xstream and so so

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Review by ahmed82 — COMMENTED** [review]
lgtm

**Comment by moremind** [comment]
please check all tools

**Comment by renzhuyan** [comment]
> please check all tools

xstream has reached 4.18, I found these others, which ones need to be upgraded?

**Comment by renzhuyan** [comment]
> lgtm

I don't quite understand what you mean, can you describe it in detail?

**Review by li-keguo — APPROVED** [review]

**Pull request merged**
