### PR TITLE
[ISSUE #2836] Feat fix shell script bugFeat fix shell script bug

### PR DESCRIPTION
**Pull request by lzqdename**
// Describe your PR here; eg. Fixes #issueNo

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Review by tuohai666 — CHANGES_REQUESTED** [review]
Change the `pgrep -f java` to` awk '{print $2}'` will make the script work in host machine but fail in container.

**Review by tuohai666 — CHANGES_REQUESTED** [review]
This problem was introduced by this issue https://github.com/apache/incubator-shenyu/issues/2338 to solve a problem in container.
Please go through https://github.com/apache/incubator-shenyu/issues/2338 and make sure the fix can work in a container.

**Comment by lzqdename** [comment]
> Change the `pgrep -f java` to` awk '{print $2}'` will make the script work in host machine but fail in container.

to execute different script command based on the run env is physical machine or docker , 
what is your opinion?

**Comment by lahmXu** [comment]
> > Change the `pgrep -f java` to` awk '{print $2}'` will make the script work in host machine but fail in container.
> 
> to execute different script command based on the run env is physical machine or docker , what is your opinion?

I tried to set
PIDS=`ps -eo pid,cmd | grep -v tail | grep -v grep | grep "$DEPLOY_DIR"| awk '{print $1}'`
and it worked，Can you help test it？

**Comment by lahmXu** [comment]
I tried to set 
```shell
PIDS=`ps -eo pid,cmd |grep -v tail|grep -v grep|grep "$DEPLOY_DIR"|awk '{print $1}'`
```
, specify the order of PID and it worked.

**Comment by tuohai666** [comment]
@lzqdename 

> > Change the `pgrep -f java` to` awk '{print $2}'` will make the script work in host machine but fail in container.
> 
> to execute different script command based on the run env is physical machine or docker , what is your opinion?

How to execute different scripts base on different envs?

**Comment by tuohai666** [comment]
> > 
> 
> there are some methods to evaluate current env using shell script

Where are they?

**Comment by lzqdename** [comment]
> > > 
> > 
> > 
> > there are some methods to evaluate current env using shell script
> 
> Where are they?

so, let me re pull a new PR later , then u can see whether the script works
PS:I have no docker env now ,you can verify it

**Pull request closed without merging**
