### PR TITLE
[ISSUE #2719] Docker image support arm architecture

### LINKED ISSUE #2719: [BUG] Docker images run failed in arm architecture
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
ShenYu version(s): 2.4.1 or latest in master
```

### Debug logs

_No response_

### Anything else?

The base image `java:openjdk-8-jre-alpine` can't support arm architecture.

### PR DESCRIPTION
**Pull request by JooKS-me**
Fix #2719 .

### CODE REVIEW

**Review by yu199195 — APPROVED** [review]

**Comment by donlinglok** [comment]
Hi, 

I am trying to pull the image from the [official docker hub](https://hub.docker.com/r/apache/shenyu-admin/tags). 
But seems both latest and 2.4.3 image of the admin and bootstrap container are marked as 'linux/**arm**64' only.
And it runs fail on windows and ubuntu with 'linux/**amd**64'.

I find this project has a GitHub Action to publish images to the docker hub, so I [forked the master branch and test the action](https://github.com/donlinglok/shenyu/runs/7607613939?check_suite_focus=true), below is the image I build, and run success on windows and ubuntu:
image

**_In conclusion, the official docker hub image may need to publish again._**  
Attached is the Github Action command log for your reference:
```
/usr/bin/docker buildx build --build-arg APP_NAME=apache-shenyu-*-admin-bin --iidfile /tmp/docker-build-push-Tdk9x6/iidfile --platform linux/amd64,linux/arm64 --tag ***/shenyuadmin:latest1 --tag ***/shenyuadmin:master --metadata-file /tmp/docker-build-push-Tdk9x6/metadata-file --push ./shenyu-dist/shenyu-admin-dist
/usr/bin/docker buildx build --build-arg APP_NAME=apache-shenyu-*-bootstrap-bin --iidfile /tmp/docker-build-push-XBGOK5/iidfile --platform linux/amd64,linux/arm64 --tag ***/shenyubootstrap:latest1 --tag ***/shenyubootstrap:master --metadata-file /tmp/docker-build-push-XBGOK5/metadata-file --push ./shenyu-dist/shenyu-bootstrap-dist
```

**Comment by JooKS-me** [comment]
@donlinglok Thanks, I have updated the image, you can try it again.

**Comment by donlinglok** [comment]
Thanks! I have tested the latest docker hub image on windows and ubuntu, and it works!

**Comment by donlinglok** [comment]
> @donlinglok Thanks, I have updated the image, you can try it again.

Sorry, just find the exposed port is wrong on the bootstrap. Should be 9195?
image

**Comment by JooKS-me** [comment]
> Sorry, just find the exposed port is wrong on the bootstrap. Should be 9195? 

The gateway should be 9195. If there are any questions, you can open an issue to describe your steps and configuration so that we can reproduce it.

**Comment by donlinglok** [comment]
> > Sorry, just find the exposed port is wrong on the bootstrap. Should be 9195?
> 
> The gateway should be 9195. If there are any questions, you can open an issue to describe your steps and configuration so that we can reproduce it.

Sorry for my mistake, all image problem is solved after the fix! Thank you!

**Pull request merged**
