### PR TITLE
refactor: move admin-config to resource directory and extract common dependencies to pom.xml

### PR DESCRIPTION
**Pull request by CarolineZhang666**
refactor: move admin-config to resource directory and extract common dependencies to pom.xml

Make sure that:

- [X] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by CarolineZhang666** [comment]
@flycash, please help to review this PR

**Comment by midnight2104** [comment]
Hi, please  merge master branch to resolve conflict before pr. And pls modify your title name by [Apache ShenYu Issue And Pull Request](https://shenyu.apache.org/community/issue-pr/) . Your pr name like this: [ISSUE #your issue No.] refactor: move admin-config to resource directory and extract common dependencies to pom.xml

**Review by flycash — COMMENTED** [review]
Good, please resolve conflicts and the it could be merged!

**Comment by CarolineZhang666** [comment]
@flycash, please help to review this PR

**Comment by CarolineZhang666** [comment]
@flycash, please help to check this PR

**Comment by CarolineZhang666** [comment]
@flycash, please help to review this PR

**Review by flycash — DISMISSED** [review]

**Comment by flycash** [comment]
LGTM

**Comment by dengliming** [comment]
@CarolineZhang666 Please check the ci.

**Comment by flycash** [comment]
@CarolineZhang666 please check the CI, there maybe some version conflicts of okhttp library

**Comment by midnight2104** [comment]
hi, @CarolineZhang666 , you need to resolve conflict and check ci , then resubmit. if you have any question? please contact me.

**Review by dengliming — APPROVED** [review]

**Pull request merged**
